require 'nokogiri'
require 'open-uri'
require_relative './craigslister/item_searcher'
require_relative './craigslister/post_scraper'
require_relative './craigslister/post'
require_relative './craigslister/main'
