require 'nokogiri'
require 'open-uri'
require_relative './craigslister/scraper'
require_relative './craigslister/post_scraper'
require_relative './craigslister/post'
require_relative './craigslister/craigslister'
